In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv( 'adult.csv' )
data.head()

age  workclass  fnlwgt     education  educational-num      marital-status  \
0   25    Private  226802          11th                7       Never-married   
1   38    Private   89814       HS-grad                9  Married-civ-spouse   
2   28  Local-gov  336951    Assoc-acdm               12  Married-civ-spouse   
3   44    Private  160323  Some-college               10  Married-civ-spouse   
4   18          ?  103497  Some-college               10       Never-married   

          occupation relationship   race  gender  capital-gain  capital-loss  \
0  Machine-op-inspct    Own-child  Black    Male             0             0   
1    Farming-fishing      Husband  White    Male             0             0   
2    Protective-serv      Husband  White    Male             0             0   
3  Machine-op-inspct      Husband  Black    Male          7688             0   
4                  ?    Own-child  White  Female             0             0   

   hours-per-week native-country income  
0              40  United-States  <=50K  
1              50  United-States  <=50K  
2              40  United-States   >50K  
3              40  United-States   >50K  
4              30  United-States  <=50K

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   age              48842 non-null  int64 
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64 
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64 
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64 
 11  capital-loss     48842 non-null  int64 
 12  hours-per-week   48842 non-null  int64 
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB


In [4]:
selectedColumns = data[ [ 'age', 'education', 'hours-per-week' ] ]
X = pd.get_dummies( selectedColumns, columns = [ 'education' ] )
X.head()

age  hours-per-week  education_10th  education_11th  education_12th  \
0   25              40               0               1               0   
1   38              50               0               0               0   
2   28              40               0               0               0   
3   44              40               0               0               0   
4   18              30               0               0               0   

   education_1st-4th  education_5th-6th  education_7th-8th  education_9th  \
0                  0                  0                  0              0   
1                  0                  0                  0              0   
2                  0                  0                  0              0   
3                  0                  0                  0              0   
4                  0                  0                  0              0   

   education_Assoc-acdm  education_Assoc-voc  education_Bachelors  \
0                     0                    0                    0   
1                     0                    0                    0   
2                     1                    0                    0   
3                     0                    0                    0   
4                     0                    0                    0   

   education_Doctorate  education_HS-grad  education_Masters  \
0                    0                  0                  0   
1                    0                  1                  0   
2                    0                  0                  0   
3                    0                  0                  0   
4                    0                  0                  0   

   education_Preschool  education_Prof-school  education_Some-college  
0                    0                      0                       0  
1                    0                      0                       0  
2                    0                      0                       0  
3                    0                      0                       1  
4                    0                      0                       1

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [6]:
le.fit( data['income'] )

LabelEncoder()

In [7]:
le.classes_

array(['<=50K', '>50K'], dtype=object)

In [8]:
le.transform( [ '<=50K', '<=50K', '>50K' ] )

array([0, 0, 1])

In [9]:
y = pd.Series( data = le.transform( data['income'] ) )
y.head()

0    0
1    0
2    1
3    1
4    0
dtype: int64

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [12]:
X

age  hours-per-week  education_10th  education_11th  education_12th  \
0       25              40               0               1               0   
1       38              50               0               0               0   
2       28              40               0               0               0   
3       44              40               0               0               0   
4       18              30               0               0               0   
...    ...             ...             ...             ...             ...   
48837   27              38               0               0               0   
48838   40              40               0               0               0   
48839   58              40               0               0               0   
48840   22              20               0               0               0   
48841   52              40               0               0               0   

       education_1st-4th  education_5th-6th  education_7th-8th  education_9th  \
0                      0                  0                  0              0   
1                      0                  0                  0              0   
2                      0                  0                  0              0   
3                      0                  0                  0              0   
4                      0                  0                  0              0   
...                  ...                ...                ...            ...   
48837                  0                  0                  0              0   
48838                  0                  0                  0              0   
48839                  0                  0                  0              0   
48840                  0                  0                  0              0   
48841                  0                  0                  0              0   

       education_Assoc-acdm  education_Assoc-voc  education_Bachelors  \
0                         0                    0                    0   
1                         0                    0                    0   
2                         1                    0                    0   
3                         0                    0                    0   
4                         0                    0                    0   
...                     ...                  ...                  ...   
48837                     1                    0                    0   
48838                     0                    0                    0   
48839                     0                    0                    0   
48840                     0                    0                    0   
48841                     0                    0                    0   

       education_Doctorate  education_HS-grad  education_Masters  \
0                        0                  0                  0   
1                        0                  1                  0   
2                        0                  0                  0   
3                        0                  0                  0   
4                        0                  0                  0   
...                    ...                ...                ...   
48837                    0                  0                  0   
48838                    0                  1                  0   
48839                    0                  1                  0   
48840                    0                  1                  0   
48841                    0                  1                  0   

       education_Preschool  education_Prof-school  education_Some-college  
0                        0                      0                       0  
1                        0                      0                       0  
2                        0                      0                       0  
3                        0                      0                       1  
4                      

In [13]:
model.fit( X_train, y_train )

/Users/alinaomelaeva/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
model.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [15]:
model.score(X_train, y_train)

0.7888209658077159

In [16]:
model.score(X_test, y_test)

0.7941035965331331

In [17]:
from sklearn.svm import SVC
model_svm = make_pipeline(StandardScaler(), SVC(gamma ='auto'))
model_svm.fit( X_train, y_train )

Pipeline(memory=None,
         steps=[('standardscaler',
                 StandardScaler(copy=True, with_mean=True, with_std=True)),
                ('svc',
                 SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                     decision_function_shape='ovr', degree=3, gamma='auto',
                     kernel='rbf', max_iter=-1, probability=False,
                     random_state=None, shrinking=True, tol=0.001,
                     verbose=False))],
         verbose=False)

In [18]:
model_svm.predict( X_test )

array([0, 0, 1, ..., 0, 0, 0])

In [19]:
model_svm.score(X_train, y_train)

0.7978297113106555

In [20]:
model_svm.score(X_test, y_test)

0.8028390090766396

In [21]:
model_svm_1 = make_pipeline(SVC(gamma ='auto'))
model_svm_1.fit( X_train, y_train )
model_svm_1.predict( X_test )
print(model_svm_1.score(X_train, y_train))
print(model_svm_1.score(X_test, y_test))

0.8013103629822458
0.8007234013512591
