### Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [1]:
import numpy as np

N = 10
x_array = np.arange(N - 1, -1, -1)
x_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [2]:
# x_array = np.arange(N - 1, -1, -1)
x_matrix = np.diag(x_array)
print(x_matrix)
print(np.trace(x_matrix))

[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


### Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [3]:
from numpy import linalg

factor_array = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
result_array = np.array([4, 12, -3])
result = linalg.solve(factor_array, result_array)
print(f'x = {result[0]}\ny = {result[1]}\nz = {result[2]}')

x = 0.4666666666666668
y = 3.844444444444444
z = -5.555555555555555


### Задание 4

In [4]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [5]:
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [6]:
#нахождение макисмального значения из косинусов имеющихся векторов и нового
nearest = max(enumerate([cosine(x, next_user_stats) for x in users_stats]), key=(lambda x: x[1]))
print(f'Наиболее похожий на next_user_stats пользователь имеет ID {nearest[0] + 1}')

Наиболее похожий на next_user_stats пользователь имеет ID 8
